### ISSUE TITLE
Not working in Win 10

### ISSUE THREAD

**Issue by Delie** [ruyadorno/ntl#7]
Just had a play in Win 10.  Although the menu works, nothing happens after you press enter.  I'm guessing it has a problem with the Exec() bit.  Any thoughts?

**Comment by ruyadorno** [comment]
hi @Delie thanks for reporting this, apparently the method `ntl` is using to invoke the scripts seems to have some issues with windows, I tried switching to use a more windows-friendly command, can you please try it and let me know how it works?

Just reinstall **ntl** from its github master branch:

```sh
npm uninstall -g ntl
npm install -g ruyadorno/ntl#master
```

**Comment by Delie** [comment]
Yes,  that fixed it!  You can now select and run scripts just fine!  Very handy little script :+1: 

One thing i did notice though - if you run a script that doesn't end automatically (e.g. a watch, or a dev server) it throws an error when you quit the task.  It's not a big problem, but I thought it was worth mentioning!  See below:

```
[default] Checking started in a separate process...
[default] Ok, 0.354 sec.
^CTerminate batch job (Y/N)? y
readline.js:945
            throw err;
            ^

Error: Command failed: npm run server
    at checkExecSyncError (child_process.js:486:13)
    at execSync (child_process.js:526:13)
    at C:\Users\XYZ\AppData\Roaming\npm\node_modules\ntl\index.js:40:4
    at Array.forEach (native)
    at onPrompt [as completed] (C:\Users\XYZ\AppData\Roaming\npm\node_modules\ntl\index.js:39:10)
    at PromptUI.onCompletion (C:\Users\XYZ\AppData\Roaming\npm\node_modules\ntl\node_modules\inquirer\lib\ui\prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Users\XYZ\AppData\Roaming\npm\node_modules\ntl\node_modules\rx-lite\rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\XYZ\AppData\Roaming\npm\node_modules\ntl\node_modules\rx-lite\rx.lite.js:1489:14)
    at Subject.Rx.Subject.addProperties.onCompleted (C:\Users\XYZ\AppData\Roaming\npm\node_modules\ntl\node_modules\rx-lite\rx.lite.js:5871:19)
    at Subject.tryCatcher (C:\Users\XYZ\AppData\Roaming\npm\node_modules\ntl\node_modules\rx-lite\rx.lite.js:63:31)
 Terminate batch job (Y/N)? y
```

**Comment by ruyadorno** [comment]
awesome! I'll make a new release with the fix, thank you very much for reporting it @Delie 🎉

**Comment by Delie** [comment]
Excellent, thank you @ruyadorno ! :+1:
